services:
  frontend:
    ports:
      - "3000:3000"
    environment:
      - "BACKEND=http://backend"
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend

  backend:
    ports: 
      - "8000:80"
    environment:
      - "DATABASE=db:8000"
      - "MINIO_HOSTNAME=minio:9000"
    build:
      context: .
      dockerfile: Dockerfile.backend

  db:
    ports:
      - "8001:8000"
    image: surrealdb/surrealdb:latest
    command: start --log trace --user root --pass root file:///db
    volumes:
      - "./db:/db"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - "./data:/data"
