FROM python:3.10-bullseye
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
RUN apt update -y && apt upgrade -y
RUN apt install imagemagick -y
EXPOSE 80

RUN python3 -m pip install poetry
WORKDIR /backend 
COPY ./backend/poetry.lock ./backend/pyproject.toml ./
RUN poetry config virtualenvs.in-project true --local
RUN poetry install --no-dev
COPY ./backend .
ENV DATABASE=postgresql+asyncpg://postgres:postgres@db:5432/clipselect 
ENTRYPOINT /backend/backend_runner.sh

