FROM python:3.10-bullseye
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV BACKEND=http://backend 
RUN apt update -y && apt upgrade -y
EXPOSE 80

RUN python3 -m pip install poetry
WORKDIR /exporter
COPY ./exporter/poetry.lock ./exporter/pyproject.toml ./
RUN poetry config virtualenvs.in-project true --local
RUN poetry install --no-dev
COPY ./exporter .
ENTRYPOINT /exporter/exporter_runner.sh

