services:
  frontend:
    ports:
      - "3000:3000"
    image: hakiergrzonzo/kronikarz-frontend:main
    environment:
      - "BACKEND=http://backend"
    depends_on:
      - backend

  backend:
    environment:
      - "DATABASE=db:8000"
      - "MINIO_HOSTNAME=minio:9000"
    image: hakiergrzonzo/kornikarz-backend:main

  db:
    image: surrealdb/surrealdb:latest
    command: start --log trace --user root --pass root file:///db
    volumes:
      - "/home/glusterfs/kronikarz/db:/db"

  minio:
    image: minio/minio
    ports:
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - "./data:/data"
